import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  "https://oixsotjrvqvbneqpzakg.supabase.co",
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9peHNvdGpydnF2Ym5lcXB6YWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE1NTc1MzksImV4cCI6MjA5NzEzMzUzOX0.eY-VjYPl88WfMjiENb2TBe6TQ5i1u2RXCL_XBPlDOt0"
);

// F.I.xlsx에서 추출한 전체 126개 종목
const stocks = [
  { ticker: "AAPL", name_kr: "애플", name_en: "Apple Inc.", sector: "Technology" },
  { ticker: "ABNB", name_kr: "에어비앤비" },
  { ticker: "ADBE", name_kr: "어도비" },
  { ticker: "ADI", name_kr: "아날로그 디바이스" },
  { ticker: "ADSK", name_kr: "오토데스크" },
  { ticker: "AEP", name_kr: "아메리칸 일렉트릭" },
  { ticker: "AMAT", name_kr: "어플라이드 머티어리얼즈" },
  { ticker: "AMD", name_kr: "AMD" },
  { ticker: "AMGN", name_kr: "암젠" },
  { ticker: "AMZN", name_kr: "아마존" },
  { ticker: "APP", name_kr: "앱러빈" },
  { ticker: "ARM", name_kr: "암(ARM)" },
  { ticker: "ASML", name_kr: "ASML" },
  { ticker: "AVGO", name_kr: "브로드컴" },
  { ticker: "AXON", name_kr: "액슨 엔터프라이즈" },
  { ticker: "AXP", name_kr: "아메리칸 익스프레스" },
  { ticker: "AZN", name_kr: "아스트라제네카" },
  { ticker: "BA", name_kr: "보잉" },
  { ticker: "BIIB", name_kr: "바이오젠" },
  { ticker: "BKNG", name_kr: "부킹 홀딩스" },
  { ticker: "BKR", name_kr: "베이커 휴즈" },
  { ticker: "BRK.B", name_kr: "버크셔 해서웨이 B" },
  { ticker: "CAT", name_kr: "캐터필러" },
  { ticker: "CCEP", name_kr: "코카콜라 유로퍼시픽" },
  { ticker: "CDNS", name_kr: "케이던스 디자인" },
  { ticker: "CEG", name_kr: "컨스텔레이션 에너지" },
  { ticker: "CMCSA", name_kr: "컴캐스트" },
  { ticker: "COST", name_kr: "코스트코" },
  { ticker: "CPRT", name_kr: "코파트" },
  { ticker: "CRM", name_kr: "세일즈포스" },
  { ticker: "CRWD", name_kr: "크라우드스트라이크" },
  { ticker: "CSCO", name_kr: "시스코 시스템즈" },
  { ticker: "CSGP", name_kr: "코스타 그룹" },
  { ticker: "CSX", name_kr: "CSX" },
  { ticker: "CTAS", name_kr: "신타스" },
  { ticker: "CTSH", name_kr: "코그니전트" },
  { ticker: "CVX", name_kr: "쉐브론" },
  { ticker: "DASH", name_kr: "도어대시" },
  { ticker: "DDOG", name_kr: "데이터독" },
  { ticker: "DIS", name_kr: "월트 디즈니" },
  { ticker: "DXCM", name_kr: "덱스콤" },
  { ticker: "EA", name_kr: "일렉트로닉 아츠" },
  { ticker: "EXC", name_kr: "엑셀론" },
  { ticker: "EXPE", name_kr: "익스피디아" },
  { ticker: "FANG", name_kr: "다이아몬드백 에너지" },
  { ticker: "FAST", name_kr: "패스널" },
  { ticker: "FTNT", name_kr: "포티넷" },
  { ticker: "GEHC", name_kr: "GE 헬스케어" },
  { ticker: "GILD", name_kr: "길리어드 사이언스" },
  { ticker: "GLW", name_kr: "코닝" },
  { ticker: "GOOG", name_kr: "알파벳 C (구글)" },
  { ticker: "GOOGL", name_kr: "알파벳 A (구글)" },
  { ticker: "GS", name_kr: "골드만삭스" },
  { ticker: "HD", name_kr: "홈디포" },
  { ticker: "HON", name_kr: "하니웰" },
  { ticker: "IBM", name_kr: "IBM" },
  { ticker: "IDXX", name_kr: "아이덱스 랩스" },
  { ticker: "INSM", name_kr: "인스메드" },
  { ticker: "INTC", name_kr: "인텔" },
  { ticker: "INTU", name_kr: "인튜이트" },
  { ticker: "ISRG", name_kr: "인튜이티브 서지컬" },
  { ticker: "JNJ", name_kr: "존슨앤존슨" },
  { ticker: "JPM", name_kr: "제이피모건 체이스" },
  { ticker: "KDP", name_kr: "큐리그 닥터페퍼" },
  { ticker: "KHC", name_kr: "크래프트 하인즈" },
  { ticker: "KLAC", name_kr: "KLA" },
  { ticker: "KO", name_kr: "코카콜라" },
  { ticker: "LIN", name_kr: "린데" },
  { ticker: "LLY", name_kr: "일라이 릴리" },
  { ticker: "LRCX", name_kr: "램 리서치" },
  { ticker: "LULU", name_kr: "Lululemon" },
  { ticker: "MA", name_kr: "마스터카드" },
  { ticker: "MAR", name_kr: "매리어트" },
  { ticker: "MCHP", name_kr: "마이크로칩" },
  { ticker: "MDLZ", name_kr: "몬델리즈" },
  { ticker: "MELI", name_kr: "메르카도리브레" },
  { ticker: "META", name_kr: "메타 플랫폼스" },
  { ticker: "MMM", name_kr: "3M" },
  { ticker: "MNST", name_kr: "몬스터 베버리지" },
  { ticker: "MRK", name_kr: "머크" },
  { ticker: "MRNA", name_kr: "모더나" },
  { ticker: "MRVL", name_kr: "마벨 테크놀로지" },
  { ticker: "MSFT", name_kr: "마이크로소프트" },
  { ticker: "MU", name_kr: "마이크론" },
  { ticker: "NEE", name_kr: "넥스트에라 에너지" },
  { ticker: "NFLX", name_kr: "넷플릭스" },
  { ticker: "NKE", name_kr: "나이키" },
  { ticker: "NVDA", name_kr: "엔비디아" },
  { ticker: "ODFL", name_kr: "올드 도미니언" },
  { ticker: "ORCL", name_kr: "오라클" },
  { ticker: "ORLY", name_kr: "오라일리 오토모티브" },
  { ticker: "PAYX", name_kr: "페이체크" },
  { ticker: "PCAR", name_kr: "패카" },
  { ticker: "PDD", name_kr: "PDD 홀딩스(핀둬둬)" },
  { ticker: "PEP", name_kr: "펩시코" },
  { ticker: "PG", name_kr: "프록터&갬블 (P&G)" },
  { ticker: "PLTR", name_kr: "팔란티어" },
  { ticker: "PYPL", name_kr: "페이팔" },
  { ticker: "QCOM", name_kr: "퀄컴" },
  { ticker: "REGN", name_kr: "리제네론" },
  { ticker: "ROP", name_kr: "로퍼 테크놀로지" },
  { ticker: "ROST", name_kr: "로스 스토어" },
  { ticker: "SBUX", name_kr: "스타벅스" },
  { ticker: "SHOP", name_kr: "쇼피파이" },
  { ticker: "SHW", name_kr: "셔윈-윌리엄즈" },
  { ticker: "SNPS", name_kr: "시놉시스" },
  { ticker: "STX", name_kr: "시게이트" },
  { ticker: "TEAM", name_kr: "아틀라시안" },
  { ticker: "TMUS", name_kr: "T-모바일" },
  { ticker: "TRV", name_kr: "트래블러스" },
  { ticker: "TSLA", name_kr: "테슬라" },
  { ticker: "TTWO", name_kr: "테이크 투" },
  { ticker: "TXN", name_kr: "텍사스 인스트루먼트" },
  { ticker: "UNH", name_kr: "유나이티드헬스 그룹" },
  { ticker: "V", name_kr: "비자" },
  { ticker: "VRSK", name_kr: "베리스크" },
  { ticker: "VRTX", name_kr: "버텍스" },
  { ticker: "VZ", name_kr: "버라이즌" },
  { ticker: "WAT", name_kr: "워터스" },
  { ticker: "WBD", name_kr: "워너 브로스" },
  { ticker: "WDAY", name_kr: "워크데이" },
  { ticker: "WDC", name_kr: "웨스턴 디지털" },
  { ticker: "WMT", name_kr: "월마트" },
  { ticker: "XEL", name_kr: "엑셀 에너지" },
  { ticker: "XOM", name_kr: "엑슨모빌" },
  { ticker: "ZS", name_kr: "지스케일러" },
];

async function importStocks() {
  console.log(`Importing ${stocks.length} stocks...`);

  const { data, error } = await supabase
    .from("stocks")
    .upsert(
      stocks.map((s) => ({
        ticker: s.ticker,
        name_kr: s.name_kr ?? null,
        name_en: (s as { name_en?: string }).name_en ?? null,
        sector: (s as { sector?: string }).sector ?? null,
        currency: "USD",
      })),
      { onConflict: "ticker" }
    )
    .select();

  if (error) {
    console.error("Error:", error.message);
    process.exit(1);
  }

  console.log(`Done. Upserted ${data.length} stocks.`);
}

importStocks();
